### ISSUE TITLE
Unable to compile from source

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/parser#4]
Missing class import static net.rptools.parser.ExpressionParserTokenTypes.*

gradle.build seems to self reference older project: compile 'net.rptools.parser:parser:1.1.b24'

**Comment by jfrazierjr** [comment]
you have to build the antlr grammar first... I am assuming that the gradle has no such tasks.   Here is what I did:


C:\Users\jfraz\git\parser\src\main\antlr\net\rptools\parser>java -cp c:\jars\antlr-2.7.7.jar antlr.Tool expression.g

This created the java files: 
C:\Users\jfraz\git\parser\src\main\antlr\net\rptools\parser>dir
 Volume in drive C is Windows
 Volume Serial Number is D422-C7C1

 Directory of C:\Users\jfraz\git\parser\src\main\antlr\net\rptools\parser

2019-09-17  22:23    <DIR>          .
2019-09-17  22:23    <DIR>          ..
2019-08-28  20:44             5,274 expression.g
2019-09-17  22:23            25,848 ExpressionLexer.java
2019-09-17  22:23             5,088 ExpressionLexer.smap
2019-09-17  22:23            27,048 ExpressionParser.java
2019-09-17  22:23             6,608 ExpressionParser.smap
2019-09-17  22:23             1,036 ExpressionParserTokenTypes.java
2019-09-17  22:23               619 ExpressionParserTokenTypes.txt
               7 File(s)         71,521 bytes
               2 Dir(s)  360,748,150,784 bytes free

I then simply moved the generated .java files into the correct directory with the others of the package.

After a few build attempts, I found that each of the generated java files has a preceding " "(space) at the beginning of the package declaration on line 2 of each of the above files.  

Finally, gradle will have issues with the generated formatting, so you will need to call

C:\Users\jfraz\git\parser>gradlew spotlessApply

BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed
C:\Users\jfraz\git\parser>gradlew build

BUILD SUCCESSFUL in 4s
6 actionable tasks: 4 executed, 2 up-to-date
C:\Users\jfraz\git\parser>

**Comment by JamzTheMan** [comment]
@cwisniew Tested with a fresh clone and looks good. Should we merge it to master and create a release?

```
 2019-09-18 12:20:37 ⌚  |2.4.2| DD25T20ABGQ18 in ~/git/JamzTheMan/parser
± jamz |develop ?:1 ✗| → sdk use java 10.0.2-open

Using java version 10.0.2-open in this shell.

 2019-09-18 12:21:02 ⌚  |2.4.2| DD25T20ABGQ18 in ~/git/JamzTheMan/parser
± jamz |develop ?:1 ✗| → ./gradlew clean build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :generateGrammarSource
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:79:21: warning:nondeterminism between alts 1 and 2 of block upon
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:79:21:     k==1:NOT
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:79:21:     k==2:IDENTIFIER,NOT,PLUS,MINUS,NUMBER,HEXNUMBER,TRUE,FALSE,SINGLE_QUOTED_STRING,DOUBLE_QUOTED_STRING,LPAREN,QUESTION
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g: warning:lexical nondeterminism between rules TRUE and IDENTIFIER upon
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:     k==1:'t'
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:     k==2:'r'
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:     k==3:'u'
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g: warning:lexical nondeterminism between rules FALSE and IDENTIFIER upon
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:     k==1:'f'
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:     k==2:'a'
/Users/xpdesktop/git/JamzTheMan/parser/src/main/antlr/net/rptools/parser/expression.g:     k==3:'l'

> Task :compileJava
Note: /Users/xpdesktop/git/JamzTheMan/parser/src/main/java/net/rptools/parser/function/impl/SquareRoot.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

BUILD SUCCESSFUL in 10s
8 actionable tasks: 8 executed
```
